fn main() {
    // PSF playback is an optional, off-by-default feature. The Highly
    // Experimental emulator core has no upstream license, so it must be
    // excluded from official release builds. Local builders can opt in with
    // `cargo build --features psf` (and `git submodule update --init` first).
    if std::env::var("CARGO_FEATURE_PSF").is_ok() {
        // Ensure hebios.bin exists — needed by psf_source.rs include_bytes!.
        // This is a PS2 IOP BIOS generated by mkhebios from a Sony PS2 BIOS
        // dump. An empty placeholder lets the build succeed without a real one;
        // PS1 PSF playback still works, but PS2 PSF will fail at runtime.
        let hebios_path = std::path::Path::new("vendor/Highly_Experimental/Core/hebios.bin");
        if !hebios_path.exists() {
            std::fs::write(hebios_path, []).expect("Failed to create hebios.bin placeholder");
        }

        // Compile psflib (PSF container parser) — needs zlib for decompression.
        cc::Build::new()
            .file("vendor/psflib/psflib.c")
            .file("vendor/psflib/psf2fs.c")
            .define("HAVE_STDINT_H", None)
            .warnings(false)
            .compile("psflib");
        println!("cargo:rustc-link-lib=z");

        // Compile Highly Experimental (PS1/PS2 PSF emulator core).
        cc::Build::new()
            .file("vendor/Highly_Experimental/Core/bios.c")
            .file("vendor/Highly_Experimental/Core/iop.c")
            .file("vendor/Highly_Experimental/Core/ioptimer.c")
            .file("vendor/Highly_Experimental/Core/mkhebios.c")
            .file("vendor/Highly_Experimental/Core/psx.c")
            .file("vendor/Highly_Experimental/Core/r3000.c")
            .file("vendor/Highly_Experimental/Core/spu.c")
            .file("vendor/Highly_Experimental/Core/spucore.c")
            .file("vendor/Highly_Experimental/Core/vfs.c")
            .define("EMU_COMPILE", None)
            .define("EMU_LITTLE_ENDIAN", None)
            .define("HAVE_STDINT_H", None)
            .include("vendor/Highly_Experimental/Core")
            .warnings(false)
            .compile("highly_experimental");
    }

    tauri_build::build()
}
