import Foundation

enum MockData {
    static let tracks: [Track] = [
        Track(id: 1, persistentId: "PID001", title: "Bohemian Rhapsody", artist: "Queen", albumArtist: "Queen", album: "A Night at the Opera", genre: "Rock", composer: "Freddie Mercury", year: 1975, trackNumber: 11, trackCount: 12, discNumber: 1, discCount: 1, duration: 354, size: 8_500_000, bitRate: 256, sampleRate: 44100, playCount: 42, skipCount: 2, rating: 100, loved: true, dateAdded: "2020-01-15T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "epic", energy: 80, vibeTags: "dramatic,operatic", bpm: 72, danceability: 40, acousticness: 30, aiTaggedAt: "2024-01-01T00:00:00Z", localFilePath: nil, fileDownloaded: false),

        Track(id: 2, persistentId: "PID002", title: "Stairway to Heaven", artist: "Led Zeppelin", albumArtist: "Led Zeppelin", album: "Led Zeppelin IV", genre: "Rock", composer: "Jimmy Page, Robert Plant", year: 1971, trackNumber: 4, trackCount: 8, discNumber: 1, discCount: 1, duration: 482, size: 11_500_000, bitRate: 256, sampleRate: 44100, playCount: 35, skipCount: 1, rating: 100, loved: true, dateAdded: "2020-01-15T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "mystical", energy: 60, vibeTags: "epic,building", bpm: 82, danceability: 30, acousticness: 50, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 3, persistentId: "PID003", title: "Hotel California", artist: "Eagles", albumArtist: "Eagles", album: "Hotel California", genre: "Rock", composer: "Don Felder, Don Henley, Glenn Frey", year: 1977, trackNumber: 1, trackCount: 9, discNumber: 1, discCount: 1, duration: 391, size: 9_400_000, bitRate: 256, sampleRate: 44100, playCount: 28, skipCount: 3, rating: 80, loved: false, dateAdded: "2020-02-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "mysterious", energy: 55, vibeTags: "mellow,atmospheric", bpm: 74, danceability: 45, acousticness: 40, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 4, persistentId: "PID004", title: "Billie Jean", artist: "Michael Jackson", albumArtist: "Michael Jackson", album: "Thriller", genre: "Pop", composer: "Michael Jackson", year: 1982, trackNumber: 6, trackCount: 9, discNumber: 1, discCount: 1, duration: 294, size: 7_000_000, bitRate: 256, sampleRate: 44100, playCount: 55, skipCount: 0, rating: 100, loved: true, dateAdded: "2020-02-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "groovy", energy: 85, vibeTags: "funky,iconic", bpm: 117, danceability: 90, acousticness: 10, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 5, persistentId: "PID005", title: "Smells Like Teen Spirit", artist: "Nirvana", albumArtist: "Nirvana", album: "Nevermind", genre: "Rock", composer: "Kurt Cobain", year: 1991, trackNumber: 1, trackCount: 12, discNumber: 1, discCount: 1, duration: 301, size: 7_200_000, bitRate: 256, sampleRate: 44100, playCount: 20, skipCount: 5, rating: 80, loved: false, dateAdded: "2020-03-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "angry", energy: 95, vibeTags: "grunge,explosive", bpm: 117, danceability: 50, acousticness: 5, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 6, persistentId: "PID006", title: "Imagine", artist: "John Lennon", albumArtist: "John Lennon", album: "Imagine", genre: "Pop", composer: "John Lennon", year: 1971, trackNumber: 1, trackCount: 10, discNumber: 1, discCount: 1, duration: 187, size: 4_500_000, bitRate: 256, sampleRate: 44100, playCount: 30, skipCount: 1, rating: 100, loved: true, dateAdded: "2020-03-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "peaceful", energy: 20, vibeTags: "gentle,hopeful", bpm: 75, danceability: 20, acousticness: 80, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 7, persistentId: "PID007", title: "Superstition", artist: "Stevie Wonder", albumArtist: "Stevie Wonder", album: "Talking Book", genre: "Funk", composer: "Stevie Wonder", year: 1972, trackNumber: 1, trackCount: 10, discNumber: 1, discCount: 1, duration: 245, size: 5_900_000, bitRate: 256, sampleRate: 44100, playCount: 45, skipCount: 0, rating: 100, loved: true, dateAdded: "2020-04-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "funky", energy: 90, vibeTags: "groovy,soulful", bpm: 101, danceability: 95, acousticness: 15, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 8, persistentId: "PID008", title: "Like a Rolling Stone", artist: "Bob Dylan", albumArtist: "Bob Dylan", album: "Highway 61 Revisited", genre: "Rock", composer: "Bob Dylan", year: 1965, trackNumber: 1, trackCount: 9, discNumber: 1, discCount: 1, duration: 369, size: 8_900_000, bitRate: 256, sampleRate: 44100, playCount: 18, skipCount: 4, rating: 60, loved: false, dateAdded: "2020-04-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "rebellious", energy: 70, vibeTags: "folk-rock,poetic", bpm: 96, danceability: 35, acousticness: 35, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 9, persistentId: "PID009", title: "What's Going On", artist: "Marvin Gaye", albumArtist: "Marvin Gaye", album: "What's Going On", genre: "Soul", composer: "Marvin Gaye", year: 1971, trackNumber: 1, trackCount: 9, discNumber: 1, discCount: 1, duration: 233, size: 5_600_000, bitRate: 256, sampleRate: 44100, playCount: 22, skipCount: 0, rating: 80, loved: true, dateAdded: "2020-05-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "soulful", energy: 50, vibeTags: "smooth,conscious", bpm: 98, danceability: 60, acousticness: 30, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 10, persistentId: "PID010", title: "Purple Rain", artist: "Prince", albumArtist: "Prince and the Revolution", album: "Purple Rain", genre: "Pop", composer: "Prince", year: 1984, trackNumber: 9, trackCount: 9, discNumber: 1, discCount: 1, duration: 520, size: 12_500_000, bitRate: 256, sampleRate: 44100, playCount: 15, skipCount: 2, rating: 100, loved: true, dateAdded: "2020-05-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "emotional", energy: 75, vibeTags: "epic,passionate", bpm: 113, danceability: 40, acousticness: 20, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 11, persistentId: "PID011", title: "Respect", artist: "Aretha Franklin", albumArtist: "Aretha Franklin", album: "I Never Loved a Man the Way I Love You", genre: "Soul", composer: "Otis Redding", year: 1967, trackNumber: 1, trackCount: 12, discNumber: 1, discCount: 1, duration: 148, size: 3_600_000, bitRate: 256, sampleRate: 44100, playCount: 38, skipCount: 1, rating: 80, loved: false, dateAdded: "2020-06-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "empowering", energy: 85, vibeTags: "soulful,powerful", bpm: 115, danceability: 75, acousticness: 25, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 12, persistentId: "PID012", title: "A Day in the Life", artist: "The Beatles", albumArtist: "The Beatles", album: "Sgt. Pepper's Lonely Hearts Club Band", genre: "Rock", composer: "Lennon-McCartney", year: 1967, trackNumber: 13, trackCount: 13, discNumber: 1, discCount: 1, duration: 337, size: 8_100_000, bitRate: 256, sampleRate: 44100, playCount: 25, skipCount: 2, rating: 100, loved: true, dateAdded: "2020-06-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "dreamy", energy: 60, vibeTags: "psychedelic,orchestral", bpm: 78, danceability: 20, acousticness: 45, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 13, persistentId: "PID013", title: "Good Vibrations", artist: "The Beach Boys", albumArtist: "The Beach Boys", album: "Smiley Smile", genre: "Pop", composer: "Brian Wilson, Mike Love", year: 1966, trackNumber: 1, trackCount: 12, discNumber: 1, discCount: 1, duration: 216, size: 5_200_000, bitRate: 256, sampleRate: 44100, playCount: 19, skipCount: 3, rating: 80, loved: false, dateAdded: "2020-07-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "joyful", energy: 75, vibeTags: "sunny,harmonious", bpm: 120, danceability: 70, acousticness: 30, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 14, persistentId: "PID014", title: "Lose Yourself", artist: "Eminem", albumArtist: "Eminem", album: "8 Mile Soundtrack", genre: "Hip Hop", composer: "Eminem", year: 2002, trackNumber: 1, trackCount: 16, discNumber: 1, discCount: 1, duration: 326, size: 7_800_000, bitRate: 256, sampleRate: 44100, playCount: 40, skipCount: 1, rating: 100, loved: true, dateAdded: "2020-07-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "intense", energy: 95, vibeTags: "motivational,raw", bpm: 87, danceability: 55, acousticness: 5, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 15, persistentId: "PID015", title: "Take Five", artist: "Dave Brubeck", albumArtist: "The Dave Brubeck Quartet", album: "Time Out", genre: "Jazz", composer: "Paul Desmond", year: 1959, trackNumber: 3, trackCount: 7, discNumber: 1, discCount: 1, duration: 324, size: 7_800_000, bitRate: 256, sampleRate: 44100, playCount: 12, skipCount: 0, rating: 80, loved: true, dateAdded: "2020-08-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "cool", energy: 45, vibeTags: "jazz,smooth", bpm: 174, danceability: 50, acousticness: 85, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 16, persistentId: "PID016", title: "Clair de Lune", artist: "Claude Debussy", albumArtist: "Claude Debussy", album: "Suite bergamasque", genre: "Classical", composer: "Claude Debussy", year: 1905, trackNumber: 3, trackCount: 4, discNumber: 1, discCount: 1, duration: 302, size: 7_200_000, bitRate: 256, sampleRate: 44100, playCount: 8, skipCount: 1, rating: 80, loved: false, dateAdded: "2020-08-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "serene", energy: 10, vibeTags: "peaceful,beautiful", bpm: 0, danceability: 5, acousticness: 100, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 17, persistentId: "PID017", title: "Get Lucky", artist: "Daft Punk", albumArtist: "Daft Punk", album: "Random Access Memories", genre: "Electronic", composer: "Thomas Bangalter, Guy-Manuel de Homem-Christo, Nile Rodgers, Pharrell Williams", year: 2013, trackNumber: 8, trackCount: 13, discNumber: 1, discCount: 1, duration: 369, size: 8_900_000, bitRate: 256, sampleRate: 44100, playCount: 50, skipCount: 0, rating: 100, loved: true, dateAdded: "2020-09-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "groovy", energy: 80, vibeTags: "disco,funky", bpm: 116, danceability: 95, acousticness: 15, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 18, persistentId: "PID018", title: "Hallelujah", artist: "Jeff Buckley", albumArtist: "Jeff Buckley", album: "Grace", genre: "Rock", composer: "Leonard Cohen", year: 1994, trackNumber: 10, trackCount: 10, discNumber: 1, discCount: 1, duration: 414, size: 10_000_000, bitRate: 256, sampleRate: 44100, playCount: 16, skipCount: 0, rating: 100, loved: true, dateAdded: "2020-09-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "emotional", energy: 40, vibeTags: "haunting,beautiful", bpm: 80, danceability: 15, acousticness: 60, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 19, persistentId: "PID019", title: "Redbone", artist: "Childish Gambino", albumArtist: "Childish Gambino", album: "Awaken, My Love!", genre: "R&B", composer: "Donald Glover", year: 2016, trackNumber: 6, trackCount: 11, discNumber: 1, discCount: 1, duration: 326, size: 7_800_000, bitRate: 256, sampleRate: 44100, playCount: 33, skipCount: 2, rating: 80, loved: true, dateAdded: "2020-10-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "psychedelic", energy: 65, vibeTags: "funky,soulful", bpm: 82, danceability: 75, acousticness: 20, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),

        Track(id: 20, persistentId: "PID020", title: "Blinding Lights", artist: "The Weeknd", albumArtist: "The Weeknd", album: "After Hours", genre: "Pop", composer: "Abel Tesfaye", year: 2020, trackNumber: 9, trackCount: 14, discNumber: 1, discCount: 1, duration: 200, size: 4_800_000, bitRate: 256, sampleRate: 44100, playCount: 60, skipCount: 1, rating: 100, loved: true, dateAdded: "2020-10-01T10:00:00Z", lastPlayedAt: nil, lastSkippedAt: nil, artworkHash: nil, hasArtwork: false, mood: "energetic", energy: 90, vibeTags: "synthwave,euphoric", bpm: 171, danceability: 85, acousticness: 5, aiTaggedAt: nil, localFilePath: nil, fileDownloaded: false),
    ]

    static let playlists: [Playlist] = [
        Playlist(id: 1, persistentId: "PL001", name: "Classic Rock Essentials", isSmart: false, isFolder: false, parentId: nil, sortOrder: 0, trackCount: 8),
        Playlist(id: 2, persistentId: "PL002", name: "Chill Vibes", isSmart: false, isFolder: false, parentId: nil, sortOrder: 1, trackCount: 6),
        Playlist(id: 3, persistentId: "PL003", name: "Dance Floor", isSmart: false, isFolder: false, parentId: nil, sortOrder: 2, trackCount: 7),
    ]

    static let playlistTrackIds: [(Int64, [Int64])] = [
        (1, [1, 2, 3, 5, 8, 10, 12, 18]),           // Classic Rock
        (2, [6, 9, 15, 16, 18, 19]),                  // Chill Vibes
        (3, [4, 7, 11, 13, 14, 17, 20]),              // Dance Floor
    ]
}
